version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python -m celery -A app.tasks.celery_app worker --loglevel=INFO
    user: "celeryuser"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: python -m celery -A app.tasks.celery_app beat --loglevel=INFO
    user: "celeryuser"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  test:
    build: .
    command: pytest -v --capture=no --log-cli-level=INFO
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/pricemonitor_test
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TEST=True
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: